#211: `ListView::itemViewAttributes()` accepts Closure as parameter.
yiisoft/yii-dataview pull request #212
Opened 2024-09-08 15:26 UTC by glpzzz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

Refs #211

2024-09-08 15:35 UTC, vjik requested changes

2024-09-08 15:35 UTC, vjik commented on src/ListView.php
> +    private array|Closure $itemViewAttributes = [];
Allow `Closure` to each attribute also, for example:

```php
[
  'class' => static fn() => ...
]
```

2024-09-09 17:35 UTC, samdark requested changes

2024-09-09 17:35 UTC, samdark commented on src/ListView.php
> +                $itemViewAttributes[$i] = $attribute($data, $key, $index, $this);
This case should be mentioned in phpdoc ↑

2024-09-09 20:44 UTC, samdark commented on src/ListView.php
> +     * If this property is specified as a callback, it must return an array of attributes and have the following
```suggestion
     * If this property is specified as a function, it must return an array of attributes and have the following
```

or 

```suggestion
     * If this property is specified as a Closure, it must return an array of attributes and have the following
```

2024-09-09 20:44 UTC, samdark commented on src/ListView.php
> +     * Also, each attribute value can be a closure too, with the same signature as in:
```suggestion
     * Also, each attribute value can be a function too, with the same signature as in:
```

2024-09-09 20:44 UTC, samdark commented on src/ListView.php
> +     * @param array|Closure $values Attribute values indexed by attribute names.
Part of the description above is about this param.

2024-09-10 07:55 UTC, samdark approved these changes

2024-09-10 07:56 UTC, samdark commented
@vjik I think everything is addressed. Please re-check.

2024-09-10 17:53 UTC, vjik approved these changes

2024-09-10 17:53 UTC, merged

2024-09-10 17:56 UTC, vjik commented
@glpzzz Thanks 👍