Refactor pagination
yiisoft/yii-dataview pull request #228
Opened 2024-11-28 14:42 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
Fix #222

2024-12-06 09:21 UTC, samdark requested changes
Overall :+1: but some things to be addressed.

2024-12-06 12:11 UTC, vjik commented on config/widgets-themes.php
> -            'currentItemClass()' => ['active'],
There isn't this method in `KeysetPagination`.

2024-12-06 12:14 UTC, vjik commented on src/BaseListView.php
> +    private PaginationControlInterface|null $paginationControl = null;
I call it "control" by analogy with "PageSizeControlInterface". In forms such elements are called "control" also.

May be "widget" is better for pagination and page size also. WDYT?

2024-12-06 23:12 UTC, samdark commented on src/BaseListView.php
> +    private PaginationControlInterface|null $paginationControl = null;
Yes. I think that widget is better.

2024-12-08 14:56 UTC, vjik commented on src/BaseListView.php
> +    private PaginationControlInterface|null $paginationControl = null;
done

2024-12-08 20:08 UTC, samdark approved these changes

2024-12-09 10:02 UTC, merged